/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as CroSSRoadDBIndexImport } from './routes/croSSRoadDB/index'
import { Route as AnalysisIndexImport } from './routes/analysis/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as CroSSRoadDBSearchImport } from './routes/croSSRoadDB/search'
import { Route as CroSSRoadDBProjectProjectIdImport } from './routes/croSSRoadDB/project/$projectId'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const CroSSRoadDBIndexRoute = CroSSRoadDBIndexImport.update({
  id: '/croSSRoadDB/',
  path: '/croSSRoadDB/',
  getParentRoute: () => rootRoute,
} as any)

const AnalysisIndexRoute = AnalysisIndexImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const CroSSRoadDBSearchRoute = CroSSRoadDBSearchImport.update({
  id: '/croSSRoadDB/search',
  path: '/croSSRoadDB/search',
  getParentRoute: () => rootRoute,
} as any)

const CroSSRoadDBProjectProjectIdRoute =
  CroSSRoadDBProjectProjectIdImport.update({
    id: '/croSSRoadDB/project/$projectId',
    path: '/croSSRoadDB/project/$projectId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/croSSRoadDB/search': {
      id: '/croSSRoadDB/search'
      path: '/croSSRoadDB/search'
      fullPath: '/croSSRoadDB/search'
      preLoaderRoute: typeof CroSSRoadDBSearchImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisIndexImport
      parentRoute: typeof rootRoute
    }
    '/croSSRoadDB/': {
      id: '/croSSRoadDB/'
      path: '/croSSRoadDB'
      fullPath: '/croSSRoadDB'
      preLoaderRoute: typeof CroSSRoadDBIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/croSSRoadDB/project/$projectId': {
      id: '/croSSRoadDB/project/$projectId'
      path: '/croSSRoadDB/project/$projectId'
      fullPath: '/croSSRoadDB/project/$projectId'
      preLoaderRoute: typeof CroSSRoadDBProjectProjectIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/croSSRoadDB/search': typeof CroSSRoadDBSearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about': typeof AboutIndexRoute
  '/analysis': typeof AnalysisIndexRoute
  '/croSSRoadDB': typeof CroSSRoadDBIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/croSSRoadDB/project/$projectId': typeof CroSSRoadDBProjectProjectIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/croSSRoadDB/search': typeof CroSSRoadDBSearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about': typeof AboutIndexRoute
  '/analysis': typeof AnalysisIndexRoute
  '/croSSRoadDB': typeof CroSSRoadDBIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/croSSRoadDB/project/$projectId': typeof CroSSRoadDBProjectProjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/croSSRoadDB/search': typeof CroSSRoadDBSearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about/': typeof AboutIndexRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/croSSRoadDB/': typeof CroSSRoadDBIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/croSSRoadDB/project/$projectId': typeof CroSSRoadDBProjectProjectIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/croSSRoadDB/search'
    | '/demo/tanstack-query'
    | '/about'
    | '/analysis'
    | '/croSSRoadDB'
    | '/dashboard/'
    | '/croSSRoadDB/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/croSSRoadDB/search'
    | '/demo/tanstack-query'
    | '/about'
    | '/analysis'
    | '/croSSRoadDB'
    | '/dashboard'
    | '/croSSRoadDB/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/croSSRoadDB/search'
    | '/demo/tanstack-query'
    | '/about/'
    | '/analysis/'
    | '/croSSRoadDB/'
    | '/dashboard/'
    | '/croSSRoadDB/project/$projectId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CroSSRoadDBSearchRoute: typeof CroSSRoadDBSearchRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
  CroSSRoadDBIndexRoute: typeof CroSSRoadDBIndexRoute
  CroSSRoadDBProjectProjectIdRoute: typeof CroSSRoadDBProjectProjectIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CroSSRoadDBSearchRoute: CroSSRoadDBSearchRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AboutIndexRoute: AboutIndexRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
  CroSSRoadDBIndexRoute: CroSSRoadDBIndexRoute,
  CroSSRoadDBProjectProjectIdRoute: CroSSRoadDBProjectProjectIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/croSSRoadDB/search",
        "/demo/tanstack-query",
        "/about/",
        "/analysis/",
        "/croSSRoadDB/",
        "/croSSRoadDB/project/$projectId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/"
      ]
    },
    "/croSSRoadDB/search": {
      "filePath": "croSSRoadDB/search.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/analysis/": {
      "filePath": "analysis/index.tsx"
    },
    "/croSSRoadDB/": {
      "filePath": "croSSRoadDB/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/croSSRoadDB/project/$projectId": {
      "filePath": "croSSRoadDB/project/$projectId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
