/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CroSSRoadDBIndexRouteImport } from './routes/croSSRoadDB/index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as CroSSRoadDBSearchRouteImport } from './routes/croSSRoadDB/search'
import { Route as CroSSRoadDBProjectProjectIdRouteImport } from './routes/croSSRoadDB/project/$projectId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CroSSRoadDBIndexRoute = CroSSRoadDBIndexRouteImport.update({
  id: '/croSSRoadDB/',
  path: '/croSSRoadDB/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CroSSRoadDBSearchRoute = CroSSRoadDBSearchRouteImport.update({
  id: '/croSSRoadDB/search',
  path: '/croSSRoadDB/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CroSSRoadDBProjectProjectIdRoute =
  CroSSRoadDBProjectProjectIdRouteImport.update({
    id: '/croSSRoadDB/project/$projectId',
    path: '/croSSRoadDB/project/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/croSSRoadDB/search': typeof CroSSRoadDBSearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about/': typeof AboutIndexRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/croSSRoadDB/': typeof CroSSRoadDBIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/croSSRoadDB/project/$projectId': typeof CroSSRoadDBProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/croSSRoadDB/search': typeof CroSSRoadDBSearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about': typeof AboutIndexRoute
  '/analysis': typeof AnalysisIndexRoute
  '/croSSRoadDB': typeof CroSSRoadDBIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/croSSRoadDB/project/$projectId': typeof CroSSRoadDBProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/croSSRoadDB/search': typeof CroSSRoadDBSearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/about/': typeof AboutIndexRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/croSSRoadDB/': typeof CroSSRoadDBIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/croSSRoadDB/project/$projectId': typeof CroSSRoadDBProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/croSSRoadDB/search'
    | '/demo/tanstack-query'
    | '/about/'
    | '/analysis/'
    | '/croSSRoadDB/'
    | '/dashboard/'
    | '/croSSRoadDB/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/croSSRoadDB/search'
    | '/demo/tanstack-query'
    | '/about'
    | '/analysis'
    | '/croSSRoadDB'
    | '/dashboard'
    | '/croSSRoadDB/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/croSSRoadDB/search'
    | '/demo/tanstack-query'
    | '/about/'
    | '/analysis/'
    | '/croSSRoadDB/'
    | '/dashboard/'
    | '/croSSRoadDB/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CroSSRoadDBSearchRoute: typeof CroSSRoadDBSearchRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
  CroSSRoadDBIndexRoute: typeof CroSSRoadDBIndexRoute
  CroSSRoadDBProjectProjectIdRoute: typeof CroSSRoadDBProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/croSSRoadDB/': {
      id: '/croSSRoadDB/'
      path: '/croSSRoadDB'
      fullPath: '/croSSRoadDB/'
      preLoaderRoute: typeof CroSSRoadDBIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/croSSRoadDB/search': {
      id: '/croSSRoadDB/search'
      path: '/croSSRoadDB/search'
      fullPath: '/croSSRoadDB/search'
      preLoaderRoute: typeof CroSSRoadDBSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/croSSRoadDB/project/$projectId': {
      id: '/croSSRoadDB/project/$projectId'
      path: '/croSSRoadDB/project/$projectId'
      fullPath: '/croSSRoadDB/project/$projectId'
      preLoaderRoute: typeof CroSSRoadDBProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CroSSRoadDBSearchRoute: CroSSRoadDBSearchRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AboutIndexRoute: AboutIndexRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
  CroSSRoadDBIndexRoute: CroSSRoadDBIndexRoute,
  CroSSRoadDBProjectProjectIdRoute: CroSSRoadDBProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
